# Generated by Django 3.0.1 on 2020-01-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=30)),
                ('StudentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('standard', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
