# Generated by Django 3.0.1 on 2020-01-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=128)),
                ('StudentGroupName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(max_length=30)),
                ('result', models.CharField(max_length=50)),
                ('StudentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=55)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('standard', models.CharField(max_length=50)),
                ('students_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='ClzManApp.Class')),
                ('students_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='of_students', to='ClzManApp.Result')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModuleName', models.CharField(max_length=30)),
                ('studentID_modules', models.ManyToManyField(related_name='study_modules', to='ClzManApp.Students')),
                ('teacherID_modules', models.ManyToManyField(related_name='teach_modules', to='ClzManApp.Teachers')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ClzManApp.Teachers'),
        ),
    ]
