# Generated by Django 3.0.1 on 2020-01-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClzManApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=40)),
                ('ModuleName', models.CharField(max_length=30)),
                ('Attendance', models.CharField(max_length=30)),
            ],
        ),
    ]
