# Generated by Django 3.0.1 on 2020-02-07 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teachers_class',
        ),
    ]
